from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(354, 456)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:#191970")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 220, 281, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.check_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.check_layout.setContentsMargins(0, 0, 0, 0)
        self.check_layout.setObjectName("check_layout")
        self.check_number = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.check_number.setFont(font)
        self.check_number.setStyleSheet("color:#ffffff")
        self.check_number.setObjectName("check_number")
        self.check_layout.addWidget(self.check_number)
        self.check_upper = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.check_upper.setFont(font)
        self.check_upper.setStyleSheet("color:#ffffff")
        self.check_upper.setObjectName("check_upper")
        self.check_layout.addWidget(self.check_upper)
        self.check_special = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.check_special.setFont(font)
        self.check_special.setStyleSheet("color: #ffffff")
        self.check_special.setObjectName("check_special")
        self.check_layout.addWidget(self.check_special)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 350, 311, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.major_btn_ayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.major_btn_ayout.setContentsMargins(0, 0, 0, 0)
        self.major_btn_ayout.setObjectName("major_btn_ayout")
        self.btn_generate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.btn_generate.setFont(font)
        self.btn_generate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_generate.setStyleSheet("color: #ffffff")
        self.btn_generate.setObjectName("btn_generate")
        self.major_btn_ayout.addWidget(self.btn_generate)
        self.btn_copy = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.btn_copy.setFont(font)
        self.btn_copy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_copy.setStyleSheet("color: #ffffff")
        self.btn_copy.setObjectName("btn_copy")
        self.major_btn_ayout.addWidget(self.btn_copy)
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(0, 0, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Affect")
        font.setPointSize(18)
        font.setBold(True)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color:#ffffff")
        self.lbl_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.output_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.output_pass.setGeometry(QtCore.QRect(10, 100, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        self.output_pass.setFont(font)
        self.output_pass.setStyleSheet("color:#ffffff")
        self.output_pass.setAlignment(QtCore.Qt.AlignCenter)
        self.output_pass.setObjectName("output_pass")
        self.lbl_length = QtWidgets.QLabel(self.centralwidget)
        self.lbl_length.setGeometry(QtCore.QRect(90, 160, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.lbl_length.setFont(font)
        self.lbl_length.setStyleSheet("color:#ffffff")
        self.lbl_length.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_length.setObjectName("lbl_length")
        self.spin_box_length = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_box_length.setGeometry(QtCore.QRect(10, 160, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.spin_box_length.setFont(font)
        self.spin_box_length.setStyleSheet("color:#ffffff")
        self.spin_box_length.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_box_length.setObjectName("spin_box_length")
        self.lbl_copied = QtWidgets.QLabel(self.centralwidget)
        self.lbl_copied.setGeometry(QtCore.QRect(180, 320, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        font.setBold(True)
        self.lbl_copied.setFont(font)
        self.lbl_copied.setStyleSheet("color:#ffffff")
        self.lbl_copied.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_copied.setObjectName("lbl_copied")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240, 150, 101, 56))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.mini_btn_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.mini_btn_layout.setContentsMargins(0, 0, 0, 0)
        self.mini_btn_layout.setObjectName("mini_btn_layout")
        self.btn_save = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("color:#ffffff")
        self.btn_save.setObjectName("btn_save")
        self.mini_btn_layout.addWidget(self.btn_save)
        self.btn_clear = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("color:#ffffff")
        self.btn_clear.setObjectName("btn_clear")
        self.mini_btn_layout.addWidget(self.btn_clear)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.check_number.setText(_translate("MainWindow", "Use Number"))
        self.check_upper.setText(_translate("MainWindow", "Use Uppercase"))
        self.check_special.setText(_translate("MainWindow", "Use Special Symbols"))
        self.btn_generate.setText(_translate("MainWindow", "Generate"))
        self.btn_copy.setText(_translate("MainWindow", "Copy"))
        self.lbl_title.setText(_translate("MainWindow", "Password Generator"))
        self.lbl_length.setText(_translate("MainWindow", "Length (4 - 16)"))
        self.lbl_copied.setText(_translate("MainWindow", "Copied"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
